//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public int Id { get; set; }
        public string Link { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
        public string Error { get; set; }
        public bool IsRead { get; set; }
        public int EvaluateId { get; set; }
    }
}
